USE `musicstore`;
INSERT INTO `music` (`Nr`, `Artist`, `Song`, `Album`, `Genre`) VALUES
(1,'Pietro Lombardi', 'Call My Name', '', ''),
(2,'LMFAO', 'Party Rock Anthem', '', ''),
(3,'Jennifer Lopez & Pitbull', 'On The Floor', '', ''),
(4,'Snoop Dogg & David Guetta', 'Sweat', '', ''),
(5,'Pitbull', 'Give Me Everything', '', ''),
(6,'Adele', 'Set Fire To The Rain', '', ''),
(7,'Caro Emerald', 'A Night Like This', '', ''),
(8,'Brooke Fraser', 'Something In The Water', '', ''),
(9,'Bruno Mars', 'The Lazy Song', '', ''),
(10,'Jessie J & B.o.B', 'Price Tag', '', ''),
(11,'Jupiter Jones', 'Still', '', ''),
(12,'Tim Bendzko', 'Nur Noch Kurz Die Welt Retten', '', ''),
(13,'Sunrise Avenue', 'Hollywood Hills', '', ''),
(14,'Alexandra Stan', 'Mr. Saxobeat', '', ''),
(15,'Rihanna', 'S&M', '', ''),
(16,'David Guetta, Flo Rida & Nicki Minaj', 'Where Them Girls At', '', ''),
(17,'Martin Solveig', 'Hello', '', ''),
(18,'Aloe Blacc', 'Loving You Is Killing Me', '', ''),
(19,'Usher', 'More', '', ''),
(20,'Bag Raiders', 'Way Back Home', '', ''),
(21,'Lady Gaga', 'Born This Way', '', ''),
(22,'Frida Gold', 'Wovon Sollen Wir Traumen', '', ''),
(23,'Andreas Bourani', 'Nur In Meinem Kopf', '', ''),
(24,'Adele', 'Rolling In The Deep', '', ''),
(25,'Jedward', 'Lipstick', '', ''),
(26,'Bruno Mars', 'Grenade', '', ''),
(27,'Taio Cruz & Kylie Minogue', 'Higher', '', ''),
(28,'Chris Brown', 'Yeah 3x', '', ''),
(29,'Milow', 'You And Me (In My Pocket)', '', ''),
(30,'Chris Brown & Benny Benassi', 'Beautiful People', '', ''),
(31,'Katy Perry', 'E.T.', '', ''),
(32,'Lady Gaga', 'Judas', '', ''),
(33,'Black Eyed Peas', 'Just Can't Get Enough', '', ''),
(34,'Natasha Bedingfield', 'Pocketful Of Sunshine', '', ''),
(35,'Blue', 'I Can', '', ''),
(36,'Depeche Mode', 'Personal Jesus 2011', '', ''),
(37,'Inna', 'Sun Is Up', '', ''),
(38,'DJ Antoine, Timati & Kalenna', 'Welcome To St. Tropez', '', ''),
(39,'Sarah Engels', 'Call My Name', '', ''),
(40,'Anders & Fahrenkrog', 'Gigolo', '', '');
