USE `dc40`;
INSERT INTO `music` (`Nr`, `Artist`, `Song`, `Album`, `Genre`) VALUES
(1,'Medina', 'For altid', '', ''),
(2,'Ankerstjerne & Burhan G', 'Tag hvad du vil', '', ''),
(3,'Pitbull feat. Ne-Yo, Afrojack & Nayer', 'Give Me Everything', '', ''),
(4,'The Storm', 'Lost In The Fire', '', ''),
(5,'Alexandra Stan', 'Mr. Saxobeat', '', ''),
(6,'Bruno Mars', 'The Lazy Song', '', ''),
(7,'LMFAO feat. Lauren Bennett & GoonRock', 'Party Rock Anthem', '', ''),
(8,'Adele', 'Set Fire To The Rain', '', ''),
(9,'Svenstrup & Vendelboe feat. Nadia Malm', 'Dybt vand', '', ''),
(10,'Snoop Dogg vs. David Guetta', 'Sweat', '', ''),
(11,'Jennifer Lopez feat. Pitbull', 'On The Floor', '', ''),
(12,'Eric Amarillo', 'Om sanningen ska fram', '', ''),
(13,'Morten Hampenberg & Alexander Brown feat. Stine Bramsen', 'I Want You (To Want Me Back)', '', ''),
(14,'Chris Brown feat. Benny Benassi', 'Beautiful People', '', ''),
(15,'Rosa Lux feat. Alberte & Josefine Winding', 'Min klub foerst', '', ''),
(16,'Boy Meets Disco', 'Live Louder', '', ''),
(17,'Jasmin [DK]', 'Mit rette element', '', ''),
(18,'Adele', 'Rolling In The Deep', '', ''),
(19,'Burhan G', 'Soevnloes', '', ''),
(20,'Rihanna', 'S&M', '', ''),
(21,'Nik & Jay', 'Mod Solnedgangen', '', ''),
(22,'Coldplay', 'Every Teardrop Is A Waterfall', '', ''),
(23,'Britney Spears', 'Till The World Ends', '', ''),
(24,'L.O.C. feat. U$O', 'Momentet', '', ''),
(25,'Swedish House Mafia', 'Save The World', '', ''),
(26,'Lady GaGa', 'Judas', '', ''),
(27,'Jason Derulo', 'Don't Wanna Go Home', '', ''),
(28,'Beyonce', 'Run The World (Girls)', '', ''),
(29,'Katy Perry feat. Kanye West', 'E.T.', '', ''),
(30,'David Guetta feat. Nicki Minaj & Flo Rida', 'Where Them Girls At', '', ''),
(31,'Jessie J feat. B.o.B', 'Price Tag', '', ''),
(32,'Fallulah', 'Out Of It', '', ''),
(33,'Agnes Obel', 'Riverside', '', ''),
(34,'Bruno Mars', 'Grenade', '', ''),
(35,'Suspekt', 'Klaus Pagh', '', ''),
(36,'Lady GaGa', 'Born This Way', '', ''),
(37,'Enrique Iglesias feat. Usher', 'Dirty Dancer', '', ''),
(38,'Jamie Woon', 'Lady Luck', '', ''),
(39,'Don Omar & Lucenzo', 'Danza kuduro', '', ''),
(40,'Kato feat. Ida Corr, Camille Jones & Johnson', 'Sjus', '', '');
