USE `bcc`;
INSERT INTO `music` (`Nr`, `Artist`, `Song`, `Album`, `Genre`) VALUES
(1,'Example', 'Changed The Way You Kiss Me', '', ''),
(2,'Pitbull', 'Give Me Everything (feat. Ne-Yo, Afrojack &amp; Nayer)', '', ''),
(3,'Nicole Scherzinger', 'Right There', '', ''),
(4,'Alexandra Stan', 'Mr Saxobeat', '', ''),
(5,'Aloe Blacc', 'I Need A Dollar', '', ''),
(6,'Coldplay', 'Every Teardrop Is A Waterfall', '', ''),
(7,'LMFAO', 'Party Rock Anthem (feat. Lauren Bennett and Goonrock)', '', ''),
(8,'Bruno Mars', 'The Lazy Song', '', ''),
(9,'Jennifer Lopez', 'I'm Into You (feat. Lil Wayne)', '', ''),
(10,'Dev', 'Bass Down Low (feat. The Cataracs)', '', ''),
(11,'Chris Brown', 'Beautiful People (feat. Benny Benassi)', '', ''),
(12,'Jessie J', 'Nobody's Perfect', '', ''),
(13,'Tracy Chapman', 'Fast Car', '', ''),
(14,'Snoop Dogg', 'Sweat (David Guetta Remix)', '', ''),
(15,'Rihanna', 'California King Bed', '', ''),
(16,'Alex Guadino', 'What A Feeling (feat. Kelly Rowland)', '', ''),
(17,'The Black Eyed Peas', 'Don't Stop The Party', '', ''),
(18,'Jennifer Lopez', 'On The Floor (feat. Pitbull)', '', ''),
(19,'Nicki Minaj', 'Super Bass', '', ''),
(20,'Inna', 'Sun Is Up', '', ''),
(21,'Paramore', 'Monster', '', ''),
(22,'Swedish House Mafia', 'Save The World', '', ''),
(23,'Lady Gaga', 'Judas', '', ''),
(24,'Adele', 'Someone Like You', '', ''),
(25,'Katy B', 'Easy Please Me', '', ''),
(26,'David Guetta', 'Where Them Girls At (feat. Nicki Minaj &amp; Flo Rida)', '', ''),
(27,'Nicola Roberts', 'Beat Of My Drum', '', ''),
(28,'Lady Gaga', 'The Edge Of Glory', '', ''),
(29,'Wynter Gordon', 'Dirty Talk', '', ''),
(30,'Beyoncé', 'Run The World (Girls)', '', ''),
(31,'Jessie J', 'Price Tag (feat. B.o.B)', '', ''),
(32,'Ludovico Einaudi', 'I Giorni', '', ''),
(33,'The Saturdays', 'Notorious', '', ''),
(34,'Templecloud', 'One Big Family', '', ''),
(35,'Nero', 'Guilt', '', ''),
(36,'Nicole Scherzinger', 'Don't Hold Your Breath', '', ''),
(37,'Adele', 'Rolling In The Deep', '', ''),
(38,'Chris Brown', 'Yeah 3X', '', ''),
(39,'Lady Gaga', 'Born This Way', '', ''),
(40,'Katy Perry', 'E.T. (feat. Kanye West)', '', '');
