USE `at40`;
INSERT INTO `music` (`Nr`, `Artist`, `Song`, `Album`, `Genre`) VALUES
(1,'Katy Perry', 'E.T.', '', ''),
(2,'Black Eyed Peas', 'Just Can't Get Enough', '', ''),
(3,'Adele', 'Rolling In the Deep', '', ''),
(4,'Britney Spears', 'Till The World Ends', '', ''),
(5,'Jennifer Lopez', 'On the Floor feat. Pitbull', '', ''),
(6,'Bruno Mars', 'The Lazy Song', '', ''),
(7,'Tinie Tempah', 'Written In the Stars (feat. Eric Turner)', '', ''),
(8,'Ke$Ha', 'Blow', '', ''),
(9,'Rihanna', 'S&M', '', ''),
(10,'Jeremih', 'Down On Me ft. 50 Cent', '', ''),
(11,'Pitbull', 'Give Me Everything ft. Ne-Yo, Afrojack, &...', '', ''),
(12,'The Script', 'For the First Time', '', ''),
(13,'Jessi J', 'Price Tag (feat. B.o.B.)', '', ''),
(14,'Cee-Lo Green', 'Forget You (FU)', '', ''),
(15,'Lupe Fiasco', 'The Show Goes On', '', ''),
(16,'Pink', 'Perfect', '', ''),
(17,'New Boyz', 'Backseat ft. The Cataracs & Dev', '', ''),
(18,'Selena Gomez', 'Who Says', '', ''),
(19,'Usher', 'More', '', ''),
(20,'Wiz Khalifa', 'Roll Up', '', ''),
(21,'Hot Chelle Rae', 'Tonight, Tonight', '', ''),
(22,'Lady Gaga', 'Born this Way', '', ''),
(23,'Onerepublic', 'Good Life', '', ''),
(24,'Enrique Iglesias', 'Tonight feat. Ludacris', '', ''),
(25,'Martin Solveig & Dra...', 'Hello', '', ''),
(26,'Lady Gaga', 'The Edge of Glory', '', ''),
(27,'Mike Posner', 'Bow Chicka Wow Wow feat. Lil Wayne', '', ''),
(28,'Lmfao', 'Party Rock Anthem', '', ''),
(29,'Pitbull', 'Hey Baby (Drop It To The Floor) feat. T-Pain', '', ''),
(30,'Taylor Swift', 'The Story of Us', '', ''),
(31,'Bruno Mars', 'Grenade', '', ''),
(32,'Dr. Dre', 'I Need a Doctor feat. Eminem & Skylar Grey', '', ''),
(33,'Taio Cruz', 'Dynamite', '', ''),
(34,'Avril Lavigne', 'What The Hell', '', ''),
(35,'Diddy-Dirty Money', 'Coming Home ft. Skylar Grey', '', ''),
(36,'Lady Gaga', 'Judas', '', ''),
(37,'Pink', 'Raise Your Glass', '', ''),
(38,'Big Time Rush', 'Boyfriend ft. Snoop Dogg', '', ''),
(39,'Chris Brown', 'Look At Me Now ft. Lil Wayne', '', ''),
(40,'Shontelle', 'Say Hello to Goodbye', '', '');
