USE `r21`;
INSERT INTO `music` (`Nr`, `Artist`, `Song`, `Album`, `Genre`) VALUES
(1,'Jessie J', 'Nobody&#039;s Perfect', '', ''),
(2,'Play &amp; Win', 'Ya BB', '', ''),
(3,'Nadia Ali', 'Rapture (Avicii Rework 2011)', '', ''),
(4,'Sasha Lopez feat Broonoo', 'All my people', '', ''),
(5,'Elena', 'Midnight Sun', '', ''),
(6,'Lora', 'No more tears', '', ''),
(7,'Sak Noel', 'Loca People', '', ''),
(8,'Katy Perry feat Kanye West', 'E.T.', '', ''),
(9,'Andreea Banica', 'Sexy', '', ''),
(10,'Amna', 'Tell me why', '', ''),
(11,'Corina', 'No spleepin&#039;', '', ''),
(12,'Snoop Dogg feat David Guetta', 'Sweat', '', ''),
(13,'Connect&#039;R', 'Ring the alarm', '', ''),
(14,'Don Omar', 'Danza Kuduro', '', ''),
(15,'Jeremih feat 50 cent', 'Down on me', '', ''),
(16,'Alexandra Stan', 'Get back (ASAP)', '', ''),
(17,'DJ Project feat Giulia', 'Mi-e dor de noi', '', ''),
(18,'Dony feat Elena', 'Hot girls', '', ''),
(19,'Nick Kamarera', 'Kalya', '', ''),
(20,'Alessia', 'Find me', '', ''),
(21,'DJ Sava feat Andreea', 'Money maker', '', ''),
(22,'Mattyas', 'Missing you', '', ''),
(23,'Park Place', 'Out of time', '', ''),
(24,'Crush Feat. Alexandra Ungureanu', 'I need you more', '', ''),
(25,'Jennifer Lopez feat Pitbull', 'On The Floor', '', ''),
(26,'Fly Project', 'Goodbye', '', ''),
(27,'Matteo feat Lee More', 'Champion', '', ''),
(28,'P. Diddy feat Skylar Grey', 'Coming home', '', ''),
(29,'Pitbull feat Ne-Yo', 'Give me everything', '', ''),
(30,'Morandi', 'Midnight Train', '', ''),
(31,'Adrian Eftimie', 'Lonely', '', ''),
(32,'Toni Tone', 'Forever alive', '', ''),
(33,'Kobi Peretz', 'Some Love', '', ''),
(34,'Radio Killer', 'Lonely heart', '', ''),
(35,'Smiley', 'Dreamgirl (Radio Killer rmx)', '', ''),
(36,'Madcon feat Ameerah', 'Freaky like me', '', ''),
(37,'Giulia', 'Underrated love', '', ''),
(38,'Adrian Sana feat Beverlei Brown', 'I can&#039;t live without you', '', ''),
(39,'Black Eyed Peas', 'The Time', '', ''),
(40,'Ela Rose', 'Lovely words', '', '');
